tab_spaces = 2
max_width = 120

overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
match_block_trailing_comma = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"
imports_layout  = "HorizontalVertical"